play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]
  motions:
    give_receive:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, 1.577]
        time_from_start: 5.0
      meta:
        name: give_receive
        usage: erl
        description: 'prep to give/receive an object'

    hold_close:
      joints: ['torso_lift_joint',arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 0.10, -1.34, -0.10, 1.9, 0, 1.37, -1.59]
        time_from_start: 5.0
      meta:
        name: hold_close
        usage: erl
        description: 'hold object close to body'

    home_direct:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint, head_2_joint]
      points:
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0, 0.0]
        time_from_start: 5.0
      meta:
        name: home_direct
        usage: erl
        description: 'Go straight home'

    tbm3_give_receive:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, 0]
        time_from_start: 5.0
      meta:
        name: tbm3_give_receive
        usage: erl
        description: 'prep to give/receive an object'

    look_into_my_eyes:
      joints: ['torso_lift_joint', arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint, head_2_joint]
      points:
      - positions: [0.25, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0, 0.35]
        time_from_start: 5.0
      meta:
        name: look_into_my_eyes
        usage: erl
        description: 'facial recognition position'
