play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]
  motions:
    give_receive:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577]
        time_from_start: 0.0
      meta:
        name: give_receive
        usage: erl
        description: 'prep to give/receive an object'

    hold_close:
      joints: ['torso_lift_joint',arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.296, 0.50, -1.34, -0.70, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 0.0
      meta:
        name: hold_close
        usage: demo
        description: 'hold object close to body'
    
